<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_ad_log extends CI_Model
{

    public $table = 'tb_log';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function select_join()
    {
		$sql="SELECT tb1.*,tb2.name
			FROM tb_log as tb1, ms_user_level as tb2
			WHERE tb1.level=tb2.id;
				";
		return $this->db->query($sql)->result();
	}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('users', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('activity', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tabel', $q);
	$this->db->or_like('create_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('users', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('activity', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tabel', $q);
	$this->db->or_like('create_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $data=array(
        	'users'		=>  $this->session->userdata('username'),
        	'level'		=>  $this->session->userdata('level'),
        	'keterangan'	=>  $this->input->post('id_member',TRUE),
        	'activity'	=>  'create data pengaduan',
        	'tabel'	=>  $this->table,
        	'create_at'	=>  date('Y-m-d H:i:s'));
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_ad_log.php */
/* Location: ./application/models/Model_ad_log.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-04 06:41:44 */
/* http://harviacode.com */