<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_ad_users extends CI_Model
{

    public $table = 'ms_users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function select_join(){
		$sql="select tb1.* ,tb2.name as nama 
				from ms_users as tb1, ms_user_level as tb2 
					where tb1.level=tb2.id";
		return $this->db->query($sql)->result();
	}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $data=array(
        	'users'		=>  $this->session->userdata('username'),
        	'level'		=>  $this->session->userdata('level'),
        	'keterangan'	=>  $this->input->post('name'),
        	'tabel'	=>  $this->table,
        	'activity'	=>  'create_data_users',
        	'create_at'	=>  date('Y-m-d H:i:s'));
        	$this->db->insert('tb_log',$data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        $data=array(
        	'users'		=>  $this->session->userdata('username'),
        	'level'		=>  $this->session->userdata('level'),
        	'keterangan'	=>  $this->input->post('name'),
        	'tabel'	=>  $this->table,
        	'activity'	=>  'update_data_users',
        	'create_at'	=>  date('Y-m-d H:i:s'));
        	$this->db->insert('tb_log',$data);
    }

    // delete data
    function delete($id)
    {	
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        $data=array(
        	'users'		=>  $this->session->userdata('username'),
        	'level'		=>  $this->session->userdata('level'),
        	'tabel'	=>  $this->table,
        	'activity'	=>  'delete_data_users',
        	'create_at'	=>  date('Y-m-d H:i:s'));
        	$this->db->insert('tb_log',$data);
    }

}

/* End of file Model_ad_users.php */
/* Location: ./application/models/Model_ad_users.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 10:10:36 */
/* http://harviacode.com */